mypyapp/models.py
from . import db


class TrainingFile(db.Model):

    __tablename__ = "training_file"

    id = db.Column(db.Integer, primary_key=True)
    filePath = db.Column(db.String(512))
    label = db.Column(db.String(128))

    def __repr__(self):
        return '<TrainingFile {}>'.format(self.filePath)

mypyapp/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileRequired
from wtforms import FileField, StringField, SubmitField
from wtforms.validators import DataRequired


images = ('jpg', 'jpeg', 'png')


class AddForm(FlaskForm):
    label = StringField("Lable for the image", validators=[DataRequired()])
    file = FileField("Add new image", validators=[
                     FileRequired(), FileAllowed(images, "Only images are allowed...!")])
    submit = SubmitField("Add")


class PredictForm(FlaskForm):
    file = FileField("Send an image for label prediction", validators=[
                     FileRequired(), FileAllowed(images, "Only images are allowed...!")])
    submit = SubmitField("Predict")

mypyapp/__init__.py
import flask
from flask import Blueprint
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy

from config import Config, TestConfig

bootstrap = Bootstrap()
db = SQLAlchemy()

from .api import bp as api_bp
from .views import bp as main_bp

def create_app(conf):
    app = flask.Flask(__name__)
    app.register_blueprint(main_bp)
    app.register_blueprint(api_bp,url_prefix='/api')
    if conf == 'main':
        app.config.from_object(Config)
    elif conf == 'test':
        app.config.from_object(TestConfig)
    else:
        raise Exception('Invalid configuration token...!')

    db.init_app(app)
    if conf =='test':
        with app.app_context():
            db.create_all()
            
    bootstrap.init_app(app)
    return app

mypyapp/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__)

from mypyapp.api import images, errors

mypyapp/views.py
import os
from datetime import datetime

from flask import (Blueprint, current_app, flash, redirect, render_template,
                   request)
from werkzeug.utils import secure_filename

from . import db
from .forms import AddForm, PredictForm
from .imagemanager import ImageManager
from .models import TrainingFile

bp = Blueprint('main', __name__)


@bp.route("/")
def about():
    return render_template("about.html")


@bp.route("/add/", methods=["GET", "POST"])
def add():
    form = AddForm()
    if request.method == "POST" and form.validate_on_submit():
        f = form.file.data
        im = ImageManager(f, form.label.data)
        if im.store_image():
            flash("File uploaded successfully...!")
        else:
            flash("Error in uploading the file...!")
        return redirect(request.url)

    return render_template("add.html", form=form)


@bp.route("/predict/", methods=["GET", "POST"])
def predict():
    form = PredictForm()
    if request.method == "POST" and form.validate_on_submit():
        f = form.file.data
        im = ImageManager(f, "")
        img_label = im.predict()
        return render_template("predict.html", form=form, img_label=img_label)
    return render_template("predict.html", form=form, img_label="")


@bp.context_processor
def inject_now():
    return {"now": datetime.utcnow()}

mypyapp/templates/about.html
{% extends "layout.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% set active_page = "about" %}
{% block app_title %}
About
{% endblock %}
{% block app_content %}
<h4>Hi :)</h4>
<div class="row">
    <div class="col-md-4">
        <p>This is my first python adventure...!</p>
    </div>
</div>
{% endblock %}

mypyapp/templates/add.html
{% extends "layout.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% set active_page = "add" %}
{% block app_title %}
Add
{% endblock %}
{% block app_content %}
<h4>This page is for storing new images with labels...!</h4>
<br />
<div class="row">
    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock %}

mypyapp/templates/layout.html
{% extends 'bootstrap/base.html' %}

{% block title %}{% block app_title %}{% endblock %}{% endblock %}

{% block navbar %}
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.about') }}">MyPyAdv</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.add') }}">Add</a></li>
                <li><a href="{{ url_for('main.predict') }}">Predict</a></li>
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

{% block content %}
<div class="container">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
    <hr>
    {% block app_content %}{% endblock %}
    <hr />
    <footer>
        <p>&copy; {{now.year}}</p>
    </footer>
</div>
{% endblock %}

mypyapp/templates/predict.html
{% extends "layout.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% set active_page = "predict" %}
{% block app_title %}
Predict
{% endblock %}
{% block app_content %}
<h4>This page is for prediction...!</h4>
<br />
{% if img_label %}<h4>This label probably suits the image: {{ img_label }} ;) </h4>{% else %}{% endif %}
<br />
<div class="row">
    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock %}